{"name": "Невозможно создать пользователя если данные уже используются", "status": "passed", "start": 1719131461441, "stop": 1719131462900, "uuid": "8725551a-39e4-4a2e-aa08-73b995385308", "historyId": "0bc436b64235fc72cee575efbd5870e3", "testCaseId": "0bc436b64235fc72cee575efbd5870e3", "fullName": "tests.test_user.TestUserCreation#test_create_already_existed_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "thinkpad"}, {"name": "thread", "value": "14280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}