{"name": "Невозможно создать пользователя если данные уже используются", "status": "passed", "start": 1719747475303, "stop": 1719747475700, "uuid": "d5d0e6a7-7f65-4f8b-b9e1-f0caa21c72d1", "historyId": "0bc436b64235fc72cee575efbd5870e3", "testCaseId": "0bc436b64235fc72cee575efbd5870e3", "fullName": "tests.test_user.TestUserCreation#test_create_already_existed_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "thinkpad"}, {"name": "thread", "value": "26668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}